- lib/mock.js
As the URI must be encoded on AWS, fs.copy does not support a query in an encoded form, so we decode it first before passing it on to fs.copy.
> Decode the URI of the filepath before passing it into fs.copy

- lib/mock.js
- test/test.js
The JS `aws-sdk` allows for strings to be PUT to S3 in the `putObject` method, converting them to buffers [here](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L208-L210) — this PR replicates that functionality.
> Add ability to put strings + fix tests.

- lib/mock.js
- test/test.js
When listing objects on S3 the marker can be a partial match of a filename.
If you have the files:
```
bar.txt
baz.txt
foo.txt
```
`s3.listObject({Marker: 'baz'}, ...)`
Should get:
```
baz.txt
foo.txt
```
Also I added `ContentLength` to the getObject response. Since that is included in the aws-sdk as well.
> listObjects Marker partial matches

- lib/mock.js
- package.json
- test/test.js
In our application, we set some configuration for the AWS SDK at runtime, using code like:
```javascript
require("aws-sdk").config.update({"foo": "bar"});
```
This adds support for this in our mocks.
> Mock out AWS' config submodule

- .travis.yml
- lib/mock.js
- test/test.js
According to the AWS Javascript SDK, [listObjects](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property) should return an object with a `CommonPrefixes` list.
Please let me know if you have any questions! Thanks!
> Add CommonPrefixes property to listObjects output

- README.md
- lib/mock.js
- test/test.js
Thank you for providing a nice mock interface to use when developing against AWS.
When porting a project of mine to use it, I found that headObject was missing.  I've provided a basic implementation.  The support in headObject matches what's available in getObject metadata.
> Implement the headObject API

- Gruntfile.js
- README.md
- lib/mock.js
- test/test.js
- test/testDefaultOptions.js
The S3 api lets you set "map of parameters to bind to every request sent by this service object" in the constructor.
See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
I'm calling these parameters "default options."
This pull requests enables the default options functionality.  This required me to refactor mock.js into an instantiable object so each instance could have its own set of default options.  Unfortunately I had to touch a majority of mock.js and github doesn't ignore white space so the diff looks a lot bigger than it really is.  It might be easier to just look at mock.js than compare the diff (https://github.com/qualtrics/mock-aws-s3/blob/master/lib/mock.js)
I added a new suite of tests testDefaultOptions.js to verify the new functionality. …
> Enable default options in the S3 mock

- lib/mock.js
- package.json
- test/test.js
- test/testDefaultOptions.js
According to the spec for List Objects  http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html, in the response:
`Marker` - Indicates where in the bucket listing begins. `Marker` is included in the response if it was sent with the request. 
`NextMarker` - When response is truncated (the `IsTruncated` element value in the response is true), you can use the key name in this field as marker in the subsequent request to get next set of objects. 
Note: This (`NextMarker`) element is returned only if you have delimiter request parameter specified. If response does not include the `NextMaker` and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys.
Previously this module set the `Marker` to …
> Set NextMarker and Marker according to AWS spec for listObjects.

- lib/mock.js
- test/test.js
Prefix as an empty string worked but not specifying the Prefix at all would return no objects.
> Handle listObjects with no Prefix value specified.

- Gruntfile.js
- lib/mock.js
- package.json
- test/testBasePath.js
- test/testDefaultOptions.js
- test/testDefaultOptionsBasePath.js
- undefined/animal.json
*The original PR has been changed*
In this PR
* Added a static property to the module named "config".
It can be used like this:
```javascript
AWS.config.basePath = '/tmp/testfiles/';
var s3 = AWS.S3();
//This will create the file /tmp/testfiles/awesomebucket/file.txt
s3.putObject({Bucket: 'awesomebucket', Key: 'file.txt', Body: 'Some text' }, function(err, data) {});
```
* The current functionality with defaultOptions has changed from:
```javascript
var s3 = AWS.S3({ Bucket: '...' });
```
to:
```javascript
var s3 = AWS.S3({params: {Bucket: '...'}})
``` 
It will also work with config.basePath:
```javascript
AWS.config.basePath = '/tmp/testfiles/';
var s3 = AWS.S3({params: {Bucket: 'awesomebucket'}});
//This will create the file /tmp/testfiles/awesomebucket/file.txt
s3.putObject({Key: …
```
> Static basePath configuration and bound parameters

- lib/mock.js
When using the `marker` option with `s3.listObjects()`, only objects after the marker should be returned.  Can I assume `filtered_files` is in alphabetical order?
> Marker
Specifies the key to start with when listing objects in a bucket. Amazon S3 returns object keys in alphabetical order, starting with key after the marker in order.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html
> fix listObjects() marker implementation

- lib/mock.js
I needed "Size" as part of the return value from listObjects. It's part of the official S3 API too, see: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property
> Include Size attribute for listObjects method

- lib/mock.js
With this fix, the getObject() function answers correctly if called on a non-existing object. Please note, that not the full answer is included, just the fields that may be interesting in testing situations, such as "code", "message", "name" and "statusCode".
> fix: file not found exception on getObject

- lib/mock.js
> Add a statSync to get the file mtime and set LastModified

- README.md
- lib/mock.js
- test/test.js
Hi @MathieuLoutre 
Thanks for this library! I've found myself needing to mock object tagging and the `listObjectsV2` endpoint, so I've implemented support for them.
This PR contains the object tagging support. As with metadata, these are only stored in-memory.
> Add support for object tagging

- README.md
- lib/mock.js
- test/test.js
Hi @MathieuLoutre 
This PR contains the `listObjectsV2` support. It's built on top of `listObjects` and translates the relevant parameters to/from the old model.
This might be incomplete, but works for my use case.
> Add support for listObjectsV2

- lib/mock.js
- package-lock.json
The assumption  for `createPromisable()` method was that each API will have 3 arguments: search, options, callback. However, this is not true for most APIs, which have only 2 argument
1. Now instead we look at the actual last argument passed (Provided arguments.length is between `[2, wrappedFunc.length]`). This ensures that promise wrapper works for all APIs
2. Current `package-lock.json` has an issue which fails `npm run install`. Hence, recreated it.
This PR fixes issue #50
> fixed .promise() methods for all APIs

- lib/mock.js
- package-lock.json
- package.json
- test/test.js
- test/testBasePath.js
- test/testDefaultOptions.js
Fixes #56.
This adds a createReadStream to the mock Request object returned by calling the endpoints. If the underlying implementation returns a FakeStream object (as getObject does) the method calls the matching method of FakeStream.
This fixes the scenario where getObject is called with no callback, and the returned request object is queried for a readable stream. Test are added for the scenario in order to avoid future regressions.
> Fix Request's createReadStream

- README.md
- lib/mock.js
- package-lock.json
- package.json
- test/test.js
Mocking getSignedUrl functionality.
The url parameters are static but the Bucket name and Key are used.
Every other parameter is currently ignored because optional.
> Mock getSignedUrl functionality

- lib/mock.js
- test/test.js
This is sadly not well documented in the AWS SDK, but is supported. This interface is necessary to ensure tags are applied to both single and multipart uploads.
See aws/aws-sdk-js#1425
> Support `tags` option in `upload`

- package-lock.json
- package.json
Snyk flagged the version of underscore as vulnerable to ACE: 
https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984
It doesn't look like the vulnerable function (`template`, `templateSettings`) is being used here, so just a version bump should suffice
> Update underscore from 1.8.3 to 1.12.1

- lib/mock.js
As the title says, this PR removes an errant console.log statement that pollutes any tests which use `getSignedURL`.
> Remove console.log in getSignedURL
